# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.forward_cumsum <- function(sequence, output) {
    invisible(.Call(`_coxdev_forward_cumsum`, sequence, output))
}

.reverse_cumsums <- function(sequence, event_buffer, start_buffer, event_order, start_order, do_event = FALSE, do_start = FALSE) {
    invisible(.Call(`_coxdev_reverse_cumsums`, sequence, event_buffer, start_buffer, event_order, start_order, do_event, do_start))
}

.to_native_from_event <- function(arg, event_order, reorder_buffer) {
    invisible(.Call(`_coxdev_to_native_from_event`, arg, event_order, reorder_buffer))
}

.to_event_from_native <- function(arg, event_order, reorder_buffer) {
    invisible(.Call(`_coxdev_to_event_from_native`, arg, event_order, reorder_buffer))
}

.forward_prework <- function(status, w_avg, scaling, risk_sums, i, j, moment_buffer, arg, use_w_avg = TRUE) {
    invisible(.Call(`_coxdev_forward_prework`, status, w_avg, scaling, risk_sums, i, j, moment_buffer, arg, use_w_avg))
}

.compute_sat_loglik <- function(first, last, weight, event_order, status, W_status) {
    .Call(`_coxdev_compute_sat_loglik`, first, last, weight, event_order, status, W_status)
}

.sum_over_events <- function(event_order, start_order, first, last, start_map, scaling, status, efron, forward_cumsum_buffers, forward_scratch_buffer, value_buffer) {
    invisible(.Call(`_coxdev_sum_over_events`, event_order, start_order, first, last, start_map, scaling, status, efron, forward_cumsum_buffers, forward_scratch_buffer, value_buffer))
}

.sum_over_risk_set <- function(arg, event_order, start_order, first, last, event_map, scaling, efron, risk_sum_buffers, risk_sum_buffers_offset, reverse_cumsum_buffers, reverse_cumsum_buffers_offset) {
    invisible(.Call(`_coxdev_sum_over_risk_set`, arg, event_order, start_order, first, last, event_map, scaling, efron, risk_sum_buffers, risk_sum_buffers_offset, reverse_cumsum_buffers, reverse_cumsum_buffers_offset))
}

.cox_dev <- function(eta, sample_weight, exp_w, event_order, start_order, status, first, last, scaling, event_map, start_map, loglik_sat, T_1_term, T_2_term, grad_buffer, diag_hessian_buffer, diag_part_buffer, w_avg_buffer, event_reorder_buffers, risk_sum_buffers, forward_cumsum_buffers, forward_scratch_buffer, reverse_cumsum_buffers, have_start_times = TRUE, efron = FALSE) {
    .Call(`_coxdev_cox_dev`, eta, sample_weight, exp_w, event_order, start_order, status, first, last, scaling, event_map, start_map, loglik_sat, T_1_term, T_2_term, grad_buffer, diag_hessian_buffer, diag_part_buffer, w_avg_buffer, event_reorder_buffers, risk_sum_buffers, forward_cumsum_buffers, forward_scratch_buffer, reverse_cumsum_buffers, have_start_times, efron)
}

.hessian_matvec <- function(arg, eta, sample_weight, risk_sums, diag_part, w_avg, exp_w, event_cumsum, start_cumsum, event_order, start_order, status, first, last, scaling, event_map, start_map, risk_sum_buffers, forward_cumsum_buffers, forward_scratch_buffer, reverse_cumsum_buffers, hess_matvec_buffer, have_start_times = TRUE, efron = FALSE) {
    .Call(`_coxdev_hessian_matvec`, arg, eta, sample_weight, risk_sums, diag_part, w_avg, exp_w, event_cumsum, start_cumsum, event_order, start_order, status, first, last, scaling, event_map, start_map, risk_sum_buffers, forward_cumsum_buffers, forward_scratch_buffer, reverse_cumsum_buffers, hess_matvec_buffer, have_start_times, efron)
}

.preprocess <- function(start, event, status) {
    .Call(`_coxdev_preprocess`, start, event, status)
}

