# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.preprocess_stratified <- function(start, event, status, strata, sample_weight, efron) {
    .Call(`_coxdev_preprocess_stratified_r`, start, event, status, strata, sample_weight, efron)
}

.cox_dev_stratified <- function(wrapper_xptr, eta) {
    .Call(`_coxdev_cox_dev_stratified_r`, wrapper_xptr, eta)
}

.hessian_matvec_stratified <- function(wrapper_xptr, arg) {
    .Call(`_coxdev_hessian_matvec_stratified_r`, wrapper_xptr, arg)
}

.get_n_strata <- function(wrapper_xptr) {
    .Call(`_coxdev_get_n_strata_r`, wrapper_xptr)
}

.get_n_total <- function(wrapper_xptr) {
    .Call(`_coxdev_get_n_total_r`, wrapper_xptr)
}

.get_sample_weight <- function(wrapper_xptr) {
    .Call(`_coxdev_get_sample_weight_r`, wrapper_xptr)
}

.create_irls_state <- function(wrapper_xptr) {
    .Call(`_coxdev_create_irls_state_r`, wrapper_xptr)
}

.irls_recompute_outer <- function(irls_state_xptr, eta) {
    .Call(`_coxdev_irls_recompute_outer_r`, irls_state_xptr, eta)
}

.irls_working_weights <- function(irls_state_xptr) {
    .Call(`_coxdev_irls_working_weights_r`, irls_state_xptr)
}

.irls_working_response <- function(irls_state_xptr) {
    .Call(`_coxdev_irls_working_response_r`, irls_state_xptr)
}

.irls_residuals <- function(irls_state_xptr) {
    .Call(`_coxdev_irls_residuals_r`, irls_state_xptr)
}

.irls_current_deviance <- function(irls_state_xptr) {
    .Call(`_coxdev_irls_current_deviance_r`, irls_state_xptr)
}

.irls_weighted_inner_product <- function(irls_state_xptr, x_j) {
    .Call(`_coxdev_irls_weighted_inner_product_r`, irls_state_xptr, x_j)
}

.irls_update_residuals <- function(irls_state_xptr, delta, x_j) {
    invisible(.Call(`_coxdev_irls_update_residuals_r`, irls_state_xptr, delta, x_j))
}

.irls_reset_residuals <- function(irls_state_xptr, eta_current) {
    invisible(.Call(`_coxdev_irls_reset_residuals_r`, irls_state_xptr, eta_current))
}

